### ISSUE TITLE
OBS crashes while scene with Motion filter is 'live' while in studio mode.

### ISSUE THREAD

**Issue by GrandyB** [CatxFish/motion-filter#1]
If the scene with the motion filter applied is the currently live scene (while in studio mode), attempting to open the general OBS "Settings" will crash. It doesn't crash if it's the scene in the preview window, but does if it is live.

**Comment by CatxFish** [comment]
Fix it in 1.0.1 release.

**Comment by GrandyB** [comment]
Confirmed.
