### ISSUE TITLE
Scene duplication missing filter config

### ISSUE THREAD

**Issue by GrandyB** [CatxFish/motion-filter#2]
Duplicating scenes doesn't copy across the sources in the filters for the scene. It copies the filters themselves, the positional/movement data, but it switches all  of the sources to be disabled, so you have to go through each one, re-adding the sources. 

The hotkeys you setup for one scene also don't copy over to the new scene.

**Comment by CatxFish** [comment]
Fix it in 1.0.1 release, and also make studio-mode work , turns out they are same issue.

**Comment by GrandyB** [comment]
Yep, this seems to work, filters now have the correct sources.
