### ISSUE TITLE
How to correctly install plugin (Linux)?

### ISSUE THREAD

**Issue by ipatix** [CatxFish/motion-filter#23]
Hi, I sucessfully compiled the two plugins and now want to install them on my Linux machine.
The instructions tell to run `make install` which I did:
```
[ 50%] Built target motion-filter
[100%] Built target motion-transition
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/obs-plugins/motion-filter.so
-- Installing: /usr/local/share/obs/obs-plugins/motion-filter/
-- Installing: /usr/local/share/obs/obs-plugins/motion-filter//zh-TW.ini
-- Installing: /usr/local/share/obs/obs-plugins/motion-filter//en-US.ini
-- Installing: /usr/local/lib/obs-plugins/motion-transition.so
-- Installing: /usr/local/share/obs/obs-plugins/motion-transition/
-- Installing: /usr/local/share/obs/obs-plugins/motion-transition//zh-TW.ini
-- Installing: /usr/local/share/obs/obs-plugins/motion-transition//en-US.ini
```
However, once obs is started up, it does not seem like those plugins get loaded correctly.
They do not seem to appear in the log file either.

How do I correctly get these plugins to load / how do I install them correctly?

**Comment by norihiro** [comment]
Hi ipatix,

I'm using motion-effect on Linux and it works. The output of 'make install' looks similar as mine.
Where is the installed path of your OBS-Studio?
Do you mind to share your log file from OBS-Studio?

**Comment by mercelsantos** [comment]
Hi everyone,

What are the correct steps to install the motion motion-filter on Linux ubuntu?

I've tried the following one but no success! :(

git clone https://github.com/CatxFish/motion-filter.git
cd motion-filter
mkdir build && cd build
cmake -DLIBOBS_INCLUDE_DIR="<libobs path>" -DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo make install

**Comment by mercelsantos** [comment]
Finally, I compiled it. The question is, where should I save the files? Saved them on /usr but obs-studio doesn't load it. Any idea?

**Comment by ipatix** [comment]
> 
> 
> Hi ipatix,
> 
> I'm using motion-effect on Linux and it works. The output of 'make install' looks similar as mine.
> Where is the installed path of your OBS-Studio?
> Do you mind to share your log file from OBS-Studio?

My OBS is installed to `/usr/bin/obs` (the release from the Debian repositories).
I don't have access to the machine at the moment, but I'll try to get the log files back as soon as possible.

**Comment by mercelsantos** [comment]
It helped a lot!!!! Thanks! I was installing the motion libs in the wrong place.

In my case obs is placed on /usr/local/bin/ . Then, I had to install motion-effect/ on /usr/local/ folder.

see cmake flags specifications bellow.

sudo cmake  -DLIBOBS_LIB="/usr/share/obs/" -DLIBOBS_INCLUDE_DIR="/usr/share/obs/" -DLibObs_DIR="/snap/obs-studio/1021/usr/cmake/LibObs/" -DCMAKE_INSTALL_PREFIX=//usr/local/

**Comment by norihiro** [comment]
Hi ipatix,

Maybe you should add cmake option `-DCMAKE_INSTALL_PREFIX=/usr` as mercelsantos first commented.

**Comment by ipatix** [comment]
@norihiro That indeed solved the problem. I would have expected that OBS tries to load plugins from both directories, but apparently that is not the case.

I don't quite like the solution of non-packaged software directly in /usr, but I guess this is rather a problem with OBS and not the plugin itself.

Thanks again!

**Comment by LynetteCullens** [comment]
Oh...So I am supposed to actually build something.
