### ISSUE TITLE
Add a "do not change scale" checkbox in filter config

### ISSUE THREAD

**Issue by GrandyB** [CatxFish/motion-filter#4]
For the majority of my sources I do not wish to alter the size of during the animation - especially when it comes to text sources.. makes setting movement up rather awkward. 
I'd like to change what the text is (and in doing so, the size of it), and still have the motion work correctly, but as of right now, you have to pre-define the size of the source at its destination point, meaning text gets squashed or extended during the animation, which obviously I do not want.
Having this option as a checkbox next to the scale values in filter config seems to make the most sense to me.

**Comment by CatxFish** [comment]
Add "change scale" option in 1.0.1. Thanks for your suggestion.

**Comment by GrandyB** [comment]
Looks like this is working.

One of my sources decided to go to 90000+ size (width and height, as I've referenced to in another issue), but I'm not sure if related.

**Comment by GrandyB** [comment]
Closing this, will leave the positional issue open however.
