### ISSUE TITLE
Filter names and migration

### ISSUE THREAD

**Issue by GrandyB** [CatxFish/motion-filter#5]
I would vastly prefer having a checkbox for "round trip", rather than having a separate filter for it.
However, if this is not possible, name them with 'Motion' at the start of the name, followed by their behaviour, e.g. "Motion (one way)" and "Motion (round trip)", so they appear next to each other in the list.

Regarding migration, it's more something to think about for future patches. I had a bunch of motion filters that in this new version automatically became _one way_ filters, while I was expecting them to be round-trip ones. Had to delete and remake. Not something to fix really, just an observation.

**Comment by CatxFish** [comment]
That make sense , only need to modify language files , I'll do it later .
