### ISSUE TITLE
Populate position with current source position on button press

### ISSUE THREAD

**Issue by GrandyB** [CatxFish/motion-filter#6]
When 'Start with given position' is first ticked, populate 'Start Position X' and 'Start Position Y' with the current X/Y of the given Source (if applicable) - saves users from needing to edit the transform of every object to see what that position is.

**Comment by CatxFish** [comment]
I have a little concern about if someone disable the option accidentally , their setting will be replaced by current position. Let me think which scheme is better.

**Comment by GrandyB** [comment]
I have an idea for this - adding a little button which on click adds the current position into the x and y boxes.
Using this as practise for my first feature 👍

**Comment by GrandyB** [comment]
Aight, after many hours of battling with cmake, finally built the thing for obs64 and got this just about done - can see pull request #9 for that.

**Comment by CatxFish** [comment]
Awesome, welcome to the world .

**Comment by GrandyB** [comment]
Cheers! Thanks for being open to all of this.
